#!/bin/sh
#
# create links to dotfiles.
#
# creating links to dotfiles assures any pull updates all environs.
# be advised, that because these are hardlinked, files will be continually
# updated, but this only works if the dotfiles repo is checked out to the
# volume as the user's home directory.

CLONEDIR=$HOME"/git/dotfiles/"

cd $CLONEDIR
ln $CLONEDIR.screenrc $HOME/.screenrc
ln $CLONEDIR.tmux.conf $HOME/.tmux.conf
ln $CLONEDIR.vimrc $HOME/.vimrc
ln $CLONEDIR.zshrc $HOME/.zshrc
